### ISSUE TITLE
InBrain version 2.0.0 won't build on iOS

### ISSUE THREAD

**Issue by jsvitek** [inbrainai/unitysdk#3]
Hello,
building iOS ipa will always fail when using InBrain version 2.0.0 with error message: `Build input file cannot be found: 'path/to/xcode/project/Libraries/Plugins/iOS/InBrainSurveys/Source/InBrainSurveys-Bridging-Header.h'. Did you forget to declare this file as an output of a script phase or a custom build rule which produces it?` 

I may have missed something from the documentation but I only found that all that needs to be done is import .unitypackcage (apart from the actual implementation). 
Furthermore renaming folder `InBrainSurveys_SDK_Swift` in Plugins/iOS to `InBrainSurveys` fixes the issue but the issue I mentioned [here](https://github.com/inbrainai/unitysdk/issues/2) is still present. 

Unity version: 2020.3.38.f1
InBrain version: v.2.0.0

**Comment by susslik** [comment]
Hello @jsvitek  - thanks for reporting this!
We will take a look at the trouble and fix that asap! Will keep you posted!

**Comment by tustanivsky** [comment]
@jsvitek The .unitypackcage for InBrain SDK v2.0.0 doesn't contain `InBrainSurveys_SDK_Swift` folder anymore (it was actually renamed to `InBrainSurveys` in the most recent release). I guess this issue could arise after updating the plugin from some older version, so you can try to remove it from the project and reimport

**Comment by jsvitek** [comment]
Hi @tustanivsky, we were indeed updating from 1.5.0 to 2.0.0. After firstly removing the previous version in the project and reimporting it anew the mentioned issue is resolved. The [other one](https://github.com/inbrainai/unitysdk/issues/2) will hopefully be resolved in the separate thread.
Thanks a lot for your help
